"""empty message

Revision ID: 003de5d7c656
Revises: 8f07f2dd7b6a
Create Date: 2023-02-03 20:12:07.696806

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '003de5d7c656'
down_revision = '8f07f2dd7b6a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=False)

    # ### end Alembic commands ###
